# permissions for end users to view flows.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kardinal-operator
    app.kubernetes.io/managed-by: kustomize
  name: kardinal-flow-viewer-role
rules:
- apiGroups:
  - kardinal.kardinal.dev
  resources:
  - flows
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kardinal.kardinal.dev
  resources:
  - flows/status
  verbs:
  - get
