apiVersion: core.kardinal.dev/v1
kind: Flow
metadata:
  labels:
    app.kubernetes.io/name: kardinal-operator
    app.kubernetes.io/managed-by: kustomize
  name: flow-sample
spec:
  service: "frontend"
  image: "kurtosistech/frontend:demo-frontend"
